---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  selector: #esse é o link para exposição
    app: flask-app #  entre o service e o deployment
  ports:
    - protocol: 'TCP' #lista
      port: 5000
      targetPort: 5000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
spec: #especificação da aplicação (global)
  replicas: 4
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec: #especificação do container que vai rodar a app
      containers:
        - name: flask
          image: lmarquesdev/flask-kub-projeto